<!DOCTYPE html>
<!-- Start Header //-->
<html>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="none" />

    <title><?=$title; ?> : SonicTone Amplification</title>

    <link type="image/png" rel="shortcut icon" href="/assets/img/sonictone-icon1-16x16.png"  />
    <link rel="stylesheet" type="text/css" href="/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/assets/css/font-awesome-5.15/all.min.css" />
    <link rel="stylesheet" type="text/css" href="/assets/css/app.min.css" />

</head>

<body>

<div class="container">
    <a href="https://www.sonictoneamps.com/" target="_blank"><img src="/assets/img/sonictone-logo-white.jpg" /></a>
    <h2 class="main-header"><?=$title; ?></h2>
    <h4 class="sub-header"><?=$subtitle; ?></h4>
    <br /><br /><br /><br />
    <div class="center">
        <h4 class="error">404 Error - Page Not Found.</h4>
    </div>
    <br /><br /><br /><br />
    <div class="footer center">
        Copyright &copy; <?=date('Y'); ?>. All Rights Reserved.<br />
        SonicTone Amplification, LLC<br />
        <a href="https://www.sonictoneamps.com/" target="_blank">www.sonictoneamps.com</a>
    </div>
</div>

<script src="/assets/js/jquery-3.5.1.min.js"></script>
<script src="/assets/js/popper.min.js"></script>
<script src="/assets/js/bootstrap.min.js"></script>
<script src="/assets/js/font-awesome-5.15/all.min.js"></script>
<script src="/assets/js/app.min.js"></script>
</body>

</html>