<!DOCTYPE html>
<!-- Start Header //-->
<html>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="SonicTone Amplification" />
    <meta name="keywords" content="tube amp calculator, electronics calculator, sonictone calculator, sonictone amps calculator" />
    <meta name="description" content="The free online resource is a calculator to assist with many common formulae and equations needed when working on tube amps or other electronics." />
    <meta name="robots" content="all" />
    <meta property="og:title" content="Calculator : SonicTone Amplification" />
    <meta property="og:image" content="https://calc.sonictoneamps.com/assets/img/calc-thumb.jpg" />
    <meta property="og:description" content="The free online resource, provided by SonicTone Amplification, is a calculator to assist with many common formulae and equations needed when working on tube amps or other audio electronics." />
    <meta property="og:url" content="https://calc.sonictoneamps.com/" />
    <meta property="og:image:width" content="1024" />
    <meta property="og:image:height" content="730" />
    <meta property="og:type" content="website" />

    <title><?=$title; ?> : SonicTone Amplification</title>

    <link type="image/png" rel="shortcut icon" href="/assets/img/sonictone-icon1-16x16.png"  />
    <link rel="stylesheet" type="text/css" href="/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/assets/css/font-awesome-5.15/all.min.css" />
    <link rel="stylesheet" type="text/css" href="/assets/css/app.min.css" />

</head>

<body>

<div class="container">
    <a href="https://www.sonictoneamps.com/" target="_blank"><img src="/assets/img/sonictone-logo-white.jpg" /></a>
    <h2 class="main-header"><?=$title; ?></h2>
    <h4 class="sub-header"><?=$subtitle; ?></h4>
    <em class="warning"><strong class="error">Warning:</strong> Tube amps can contain dangerous and even lethal amounts of high voltage. Working with these voltages can be very dangerous or even fatal, so do not do so unless you are knowledgeable and skilled enough to work on tube amps.
    SonicTone Amplification is not liable for any damages, loss, injury or death due to the use of this calculator to assist in working on a tube amplifier or any electronics. Use the calculator and its results at your own risk.</em><br /><br />
    <br /><br /><br /><br />
    <div class="center">
        <h4 class="error">404 Error - Page Not Found.</h4>
    </div>
    <br /><br /><br /><br />
    <div class="footer center">
        Version <?=$version; ?><br />
        Copyright &copy; <?=date('Y'); ?>. All Rights Reserved.<br />
        SonicTone Amplification, LLC<br /><br />
        The SonicTone Logo is a registered trademark<br />of SonicTone Amplification, LLC.<br /><br />
        <a href="https://www.sonictoneamps.com/" target="_blank">www.sonictoneamps.com</a><br />
        <a href="https://github.com/nicksagona/tube-amp-calc" target="_blank"><i class="fa fab fa-github"></i> GitHub</a><br /><br />
        If you have any issues or questions about this resource,<br />please contact <a href="" class="contact-email" target="_blank"></a>
    </div>
</div>

<script src="/assets/js/jquery-3.5.1.min.js"></script>
<script src="/assets/js/popper.min.js"></script>
<script src="/assets/js/bootstrap.min.js"></script>
<script src="/assets/js/font-awesome-5.15/all.min.js"></script>
<script src="/assets/js/app.min.js"></script>
</body>

</html>
