<!DOCTYPE html>
<!-- Start Header //-->
<html>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="none" />

    <title><?=$title; ?> : SonicTone Amplification</title>

    <link type="image/png" rel="shortcut icon" href="/assets/img/sonictone-icon1-16x16.png"  />
    <link rel="stylesheet" type="text/css" href="/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/assets/css/font-awesome-5.15/all.min.css" />
    <link rel="stylesheet" type="text/css" href="/assets/css/app.min.css" />

</head>

<body>

<div class="container">
    <a href="https://www.sonictoneamps.com/" target="_blank"><img src="/assets/img/sonictone-logo-white.jpg" /></a>
    <h2 class="main-header"><?=$title; ?></h2>
    <h4 class="sub-header"><?=$subtitle; ?></h4>
    <ul class="nav nav-pills nav-fill" id="nav">
        <li class="nav-item">
            <a class="nav-link active" href="#ohms-law">Ohm's Law</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#voltage-div">Voltage</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#power">Power</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#rc-filter">RC</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#resistance-calc">Resistance</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#capacitance-calc">Capacitance</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#bias-calc">Bias</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#b-plus-calc">B+</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#ot-calc">OT</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#capacitance-chart">Cap Conv</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="https://www.ampbooks.com/mobile/amplifier-calculators/cathode-capacitor/calculator/" target="_blank">Cathode Cap Calc</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="https://www.vtadiy.com/loadline-calculators/loadline-calculator/#calculator" target="_blank">Load Line Calc</a>
        </li>
    </ul>
    <a name="ohms-law"></a>
<?=$formOhm; ?>
    <div class="container answer" id="answer-ohm"><div id="answer-ohm-box" class="answer-box alert alert-success"></div></div>
    <a name="voltage-div"></a>
<?=$formVoltageDiv; ?>
    <div class="container answer" id="answer-voltage-div"><div id="answer-voltage-div-box" class="answer-box-double alert alert-success"></div></div>
    <a name="power"></a>
<?=$formPower; ?>
    <div class="container answer" id="answer-power"><div id="answer-power-box" class="answer-box-double alert alert-success"></div></div>
    <a name="rc-filter"></a>
<?=$formFreq; ?>
    <div class="container answer" id="answer-freq"><div id="answer-freq-box" class="answer-box alert alert-success"></div></div>
    <a name="resistance-calc"></a>
<?=$formResistance; ?>
    <div class="container answer" id="answer-resistance"><div id="answer-resistance-box" class="answer-box alert alert-success"></div></div>
    <a name="capacitance-calc"></a>
<?=$formCapacitance; ?>
    <div class="container answer" id="answer-capacitance"><div id="answer-capacitance-box" class="answer-box-double alert alert-success"></div></div>
    <a name="bias-calc"></a>
<?=$formBias; ?>
    <div class="container answer-bias" id="answer-bias"><div id="answer-bias-box" class="answer-box-bias alert"></div></div>
    <a name="b-plus-calc"></a>
<?=$formBPlus; ?>
    <div class="container answer" id="answer-b-plus"><div id="answer-b-plus-box" class="answer-box alert alert-success"></div></div>
    <a name="ot-calc"></a>
<?=$formOT; ?>
    <div class="container answer" id="answer-ot"><div id="answer-ot-box" class="answer-box-double alert alert-success"></div></div>
</div>
<div class="clearfix pad"></div>
<div class="container">
    <a name="capacitance-chart"></a>
    <div><a href="#top" class="float-right small">Top</a><h3 class="center">Capacitance Conversion Chart:</h3></div>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th class="center">Microfarads (uF)</th>
                <th class="center">Nanofarads (nF)</th>
                <th class="center">Picofarads (pF)</th>
            </tr>
        </thead>
        <tbody>
<?php foreach ($farads as $faradValue): ?>
            <tr>
                <td><?=$faradValue['micro']; ?></td>
                <td><?=$faradValue['nano']; ?></td>
                <td><?=$faradValue['pico']; ?></td>
            </tr>
<?php endforeach; ?>
        </tbody>
    </table>
    <div class="footer center">
        Version <?=$version; ?><br />
        Copyright &copy; <?=date('Y'); ?>. All Rights Reserved.<br />
        SonicTone Amplification, LLC<br />
        <a href="https://www.sonictoneamps.com/" target="_blank">www.sonictoneamps.com</a>
    </div>
</div>

<script src="/assets/js/jquery-3.5.1.min.js"></script>
<script src="/assets/js/popper.min.js"></script>
<script src="/assets/js/bootstrap.min.js"></script>
<script src="/assets/js/font-awesome-5.15/all.min.js"></script>
<script src="/assets/js/app.min.js"></script>
</body>

</html>