<!DOCTYPE html>
<!-- Header //-->
<html>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="tube amp equations, common tube amp equations" />
    <meta name="description" content="This website is a quick calculator tool to help you calculate common values for tube amplifiers." />
    <meta name="author" content="Nick Sagona" />
    <meta name="robots" content="all" />

    <title>Tube Amp Common Equations</title>

    <link rel="stylesheet" type="text/css" href="/assets/app.css" />

</head>

<body>
    <div class="container-fluid">
        <div class="col-md-12">
            <h3>Tube Amplifier</h3>
            <h1>Common Equations</h1>
